name: prerelease NuGet

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    # also works with windows-latest and macos-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v1
    - name: Build solution and generate NuGet package
      run: |  
          cd FileManager
          dotnet pack -c Release -o out  
      shell: bash
    - name: Publish nuget
      run: |
           for f in D:\a\FileManager\FileManager\FileManager\out\*.nupkg
           do
             curl -vX PUT -u "[user]:${{ secrets.FILEMANAGER }}" -F package=@$f https://nuget.pkg.github.com/murunwas/
           done
      shell: bash
